### ISSUE TITLE
`_replicator` should be the only API point for the replication

### ISSUE THREAD

**Issue by benoitc** [rcouch/couch_core#10]
Today we have 2 way to handle the replication using the `_replicate` resource or by posting a new replication doc to `_replicator` database. With the _replicate handler everything is in memory while with the replicator database, tasks persist on the file system.

I propose to :
- Only use the replicator database to store tasks
- Remove all the _replicate entry point.
- Make tasks progress more accessible. It should be easier to monitor the progression of a replication.

**Comment by nrdufour** [comment]
+1 for me!
