### ISSUE TITLE
make check is failing on ubuntu 12.04 32 bit

### ISSUE THREAD

**Issue by nrdufour** [rcouch/couch_core#5]
Environment:
- ubuntu 12.04 beta
- erlang R14B04

Current log:

./test/couch_dev/bin/test_js
1..72
ok 1 all_docs
ok 2 attachment_names
ok 3 attachment_paths
ok 4 attachment_ranges
ok 5 attachment_views
ok 6 attachments
ok 7 attachments_multipart
ok 8 auth_cache
ok 9 basics
ok 10 batch_save
ok 11 bulk_docs
ok 12 changes
ok 13 coffee
ok 14 compact
ok 15 config
ok 16 conflicts
ok 17 content_negotiation
ok 18 cookie_auth
ok 19 copy_doc
ok 20 delayed_commits
ok 21 design_docs
ok 22 design_options
ok 23 design_paths
ok 24 erlang_views
ok 25 etags_head
ok 26 etags_views
not ok 27 form_submit
(new Error("Failed to execute HTTP request: Recv failure: Connection reset by peer", "/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js", 37))
Stacktrace:
        ("{}")@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js:37
        ("POST","/test_suite_db/baz",[object Object])@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/couch.js:420
        ()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/test/form_submit.js:20
        runTestConsole(27,"form_submit",(function (debug) {var db = new CouchDB("test_suite_db", {'X-Couch-Full-Commit': "false"});db.deleteDb();db.createDb();var json = "{}";var xhr = CouchDB.request("POST", "/test_suite_db/baz", {body: json});T(xhr.status == 415);result = JSON.parse(xhr.responseText);T(result.error, "bad_content_type");T(result.reason, "Invalid Content-Type header for form upload");}))@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:30
        runAllTestsConsole()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:51
        @/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:59

ok 28 http
ok 29 invalid_docids
ok 30 jsonp
ok 31 large_docs
ok 32 list_views
ok 33 lots_of_docs
ok 34 method_override
ok 35 multiple_rows
ok 36 oauth
ok 37 oauth_users_db
ok 38 proxyauth
ok 39 purge
ok 40 reader_acl
ok 41 recreate_doc
ok 42 reduce
ok 43 reduce_builtin
ok 44 reduce_false
ok 45 reduce_false_temp
ok 46 replication
ok 47 replicator_db
ok 48 replicator_db_security
ok 49 rev_stemming
ok 50 rewrite
ok 51 security_validation
ok 52 show_documents
ok 53 stats
ok 54 update_documents
ok 55 users_db
ok 56 users_db_security
ok 57 utf8
ok 58 uuids
ok 59 view_collation
ok 60 view_collation_raw
ok 61 view_compaction
ok 62 view_conflicts
not ok 63 view_errors
(new Error("Failed to execute HTTP request: Recv failure: Connection reset by peer", "/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js", 37))
Stacktrace:
        ("{\"language\":\"javascript\",\"map\":\"function(doc){}\"}")@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js:37
        ("POST","/test_suite_db/_temp_view",[object Object])@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/couch.js:420
        ()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/test/view_errors.js:63
        run_on_modified_server([object Array],(function () {var doc = {integer: 1, string: "1", array: [1, 2, 3]};T(db.save(doc).ok);var results = db.query(function (doc) {emit(doc.undef, null);});T(results.total_rows == 1);T(results.rows[0].key == null);var results = db.query(function (doc) {doc.undef();});T(results.total_rows == 0);var results = db.query(function (doc) {emit([doc._id, doc.undef], null);});T(results.total_rows == 1);T(results.rows[0].key[1] == null);var xhr = CouchDB.request("POST", "/test_suite_db/_temp_view?startkey=foo", {headers: {'Content-Type': "application/json"}, body: JSON.stringify({language: "javascript", map: "function(doc){emit(doc.integer)}"})});T(JSON.parse(xhr.responseText).error == "bad_request");var xhr = CouchDB.request("POST", "/test_suite_db/_temp_view", {headers: {'Content-Type': "application/x-www-form-urlencoded"}, body: JSON.stringify({language: "javascript", map: "function(doc){}"})});T(xhr.status == 415);var map = function (doc) {emit(doc.integer, doc.integer);};try {db.query(map, null, {group: true});T(0 == 1);} catch (e) {T(e.error == "query_parse_error");}var designDoc = {_id: "_design/test", language: "javascript", views: {no_reduce: {map: "function(doc) {emit(doc._id, null);}"}, with_reduce: {map: "function (doc) {emit(doc.integer, doc.integer)};", reduce: "function (keys, values) { return sum(values); };"}}};T(db.save(designDoc).ok);var designDoc2 = {_id: "_design/testbig", language: "javascript", views: {reduce_too_big: {map: "function (doc) {emit(doc.integer, doc.integer)};", reduce: "function (keys, values) { var chars = []; for (var i=0; i < 1000; i++) {chars.push('wazzap');};return chars; };"}}};T(db.save(designDoc2).ok);try {db.view("test/no_reduce", {group: true});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/no_reduce", {group_level: 1});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/no_reduce", {reduce: true});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}db.view("test/no_reduce", {reduce: false});TEquals(200, db.last_req.status, "reduce=false for map views (without group or group_level) is allowed");try {db.view("test/with_reduce", {group: true, reduce: false});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/with_reduce", {group_level: 1, reduce: false});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}var designDoc3 = {_id: "_design/infinite", language: "javascript", views: {infinite_loop: {map: "function(doc) {while(true){emit(doc,doc);}};"}}};T(db.save(designDoc3).ok);try {db.view("infinite/infinite_loop");T(0 == 1);} catch (e) {T(e.error == "os_process_error");}var path = "/test_suite_db/_design/test/_view/no_reduce";var xhr = CouchDB.request("POST", path, {body: "[]"});T(xhr.status == 400);result = JSON.parse(xhr.responseText);T(result.error == "bad_request");T(result.reason == "Request body must be a JSON object");var data = "{\"keys\": 1}";xhr = CouchDB.request("POST", path, {body: data});T(xhr.status == 400);result = JSON.parse(xhr.responseText);T(result.error == "bad_request");T(result.reason == "`keys` member must be a array.");var path = "/test_suite_db/_design/testbig/_view/reduce_too_big";xhr = CouchDB.request("GET", path);T(xhr.status == 500);result = JSON.parse(xhr.responseText);T(result.error == "reduce_overflow_error");try {db.query(function () {emit(null, null);}, null, {startkey: 2, endkey: 1});T(0 == 1);} catch (e) {T(e.error == "query_parse_error");T(e.reason.match(/no rows can match/i));}}))@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/couch_test_runner.js:380
        ()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/test/view_errors.js:23
        runTestConsole(63,"view_errors",(function (debug) {var db = new CouchDB("test_suite_db", {'X-Couch-Full-Commit': "true"});db.deleteDb();db.createDb();if (debug) {debugger;}run_on_modified_server([{section: "couchdb", key: "os_process_timeout", value: "500"}], function () {var doc = {integer: 1, string: "1", array: [1, 2, 3]};T(db.save(doc).ok);var results = db.query(function (doc) {emit(doc.undef, null);});T(results.total_rows == 1);T(results.rows[0].key == null);var results = db.query(function (doc) {doc.undef();});T(results.total_rows == 0);var results = db.query(function (doc) {emit([doc._id, doc.undef], null);});T(results.total_rows == 1);T(results.rows[0].key[1] == null);var xhr = CouchDB.request("POST", "/test_suite_db/_temp_view?startkey=foo", {headers: {'Content-Type': "application/json"}, body: JSON.stringify({language: "javascript", map: "function(doc){emit(doc.integer)}"})});T(JSON.parse(xhr.responseText).error == "bad_request");var xhr = CouchDB.request("POST", "/test_suite_db/_temp_view", {headers: {'Content-Type': "application/x-www-form-urlencoded"}, body: JSON.stringify({language: "javascript", map: "function(doc){}"})});T(xhr.status == 415);var map = function (doc) {emit(doc.integer, doc.integer);};try {db.query(map, null, {group: true});T(0 == 1);} catch (e) {T(e.error == "query_parse_error");}var designDoc = {_id: "_design/test", language: "javascript", views: {no_reduce: {map: "function(doc) {emit(doc._id, null);}"}, with_reduce: {map: "function (doc) {emit(doc.integer, doc.integer)};", reduce: "function (keys, values) { return sum(values); };"}}};T(db.save(designDoc).ok);var designDoc2 = {_id: "_design/testbig", language: "javascript", views: {reduce_too_big: {map: "function (doc) {emit(doc.integer, doc.integer)};", reduce: "function (keys, values) { var chars = []; for (var i=0; i < 1000; i++) {chars.push('wazzap');};return chars; };"}}};T(db.save(designDoc2).ok);try {db.view("test/no_reduce", {group: true});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/no_reduce", {group_level: 1});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/no_reduce", {reduce: true});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}db.view("test/no_reduce", {reduce: false});TEquals(200, db.last_req.status, "reduce=false for map views (without group or group_level) is allowed");try {db.view("test/with_reduce", {group: true, reduce: false});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}try {db.view("test/with_reduce", {group_level: 1, reduce: false});T(0 == 1);} catch (e) {T(db.last_req.status == 400);T(e.error == "query_parse_error");}var designDoc3 = {_id: "_design/infinite", language: "javascript", views: {infinite_loop: {map: "function(doc) {while(true){emit(doc,doc);}};"}}};T(db.save(designDoc3).ok);try {db.view("infinite/infinite_loop");T(0 == 1);} catch (e) {T(e.error == "os_process_error");}var path = "/test_suite_db/_design/test/_view/no_reduce";var xhr = CouchDB.request("POST", path, {body: "[]"});T(xhr.status == 400);result = JSON.parse(xhr.responseText);T(result.error == "bad_request");T(result.reason == "Request body must be a JSON object");var data = "{\"keys\": 1}";xhr = CouchDB.request("POST", path, {body: data});T(xhr.status == 400);result = JSON.parse(xhr.responseText);T(result.error == "bad_request");T(result.reason == "`keys` member must be a array.");var path = "/test_suite_db/_design/testbig/_view/reduce_too_big";xhr = CouchDB.request("GET", path);T(xhr.status == 500);result = JSON.parse(xhr.responseText);T(result.error == "reduce_overflow_error");try {db.query(function () {emit(null, null);}, null, {startkey: 2, endkey: 1});T(0 == 1);} catch (e) {T(e.error == "query_parse_error");T(e.reason.match(/no rows can match/i));}});}))@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:30
        runAllTestsConsole()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:51
        @/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:59

ok 64 view_include_docs
ok 65 view_multi_key_all_docs
ok 66 view_multi_key_design
ok 67 view_multi_key_temp
ok 68 view_offsets
ok 69 view_pagination
ok 70 view_sandboxing
ok 71 view_update_seq
ok 72 view_xml
Error: All JS CLI tests should pass.
Stacktrace:
    T(false,"All JS CLI tests should pass.")@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:23
    runAllTestsConsole()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:55
    @/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:59
Failed to execute script.
ok
make: **\* [js] Error 1
nrdufour@ubuntu32:~/tmp/refuge/deps/couch_core$

**Comment by nrdufour** [comment]
So #27 (form_submit) and #63 (view_errors)

**Comment by nrdufour** [comment]
I have executed the tests a second time, and I get only one test failing:

./test/couch_dev/bin/test_js
1..72
ok 1 all_docs
ok 2 attachment_names
ok 3 attachment_paths
ok 4 attachment_ranges
ok 5 attachment_views
ok 6 attachments
ok 7 attachments_multipart
ok 8 auth_cache
ok 9 basics
ok 10 batch_save
ok 11 bulk_docs
ok 12 changes
ok 13 coffee
ok 14 compact
ok 15 config
ok 16 conflicts
ok 17 content_negotiation
ok 18 cookie_auth
ok 19 copy_doc
ok 20 delayed_commits
ok 21 design_docs
ok 22 design_options
ok 23 design_paths
ok 24 erlang_views
ok 25 etags_head
ok 26 etags_views
not ok 27 form_submit
(new Error("Failed to execute HTTP request: Recv failure: Connection reset by peer", "/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js", 37))
Stacktrace:
        ("{}")@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/couch_http.js:37
        ("POST","/test_suite_db/baz",[object Object])@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/couch.js:420
        ()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/share/www/script/test/form_submit.js:20
        runTestConsole(27,"form_submit",(function (debug) {var db = new CouchDB("test_suite_db", {'X-Couch-Full-Commit': "false"});db.deleteDb();db.createDb();var json = "{}";var xhr = CouchDB.request("POST", "/test_suite_db/baz", {body: json});T(xhr.status == 415);result = JSON.parse(xhr.responseText);T(result.error, "bad_content_type");T(result.reason, "Invalid Content-Type header for form upload");}))@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:30
        runAllTestsConsole()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:51
        @/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:59

ok 28 http
ok 29 invalid_docids
ok 30 jsonp
ok 31 large_docs
ok 32 list_views
ok 33 lots_of_docs
ok 34 method_override
ok 35 multiple_rows
ok 36 oauth
ok 37 oauth_users_db
ok 38 proxyauth
ok 39 purge
ok 40 reader_acl
ok 41 recreate_doc
ok 42 reduce
ok 43 reduce_builtin
ok 44 reduce_false
ok 45 reduce_false_temp
ok 46 replication
ok 47 replicator_db
ok 48 replicator_db_security
ok 49 rev_stemming
ok 50 rewrite
ok 51 security_validation
ok 52 show_documents
ok 53 stats
ok 54 update_documents
ok 55 users_db
ok 56 users_db_security
ok 57 utf8
ok 58 uuids
ok 59 view_collation
ok 60 view_collation_raw
ok 61 view_compaction
ok 62 view_conflicts
ok 63 view_errors
ok 64 view_include_docs
ok 65 view_multi_key_all_docs
ok 66 view_multi_key_design
ok 67 view_multi_key_temp
ok 68 view_offsets
ok 69 view_pagination
ok 70 view_sandboxing
ok 71 view_update_seq
ok 72 view_xml
Error: All JS CLI tests should pass.
Stacktrace:
    T(false,"All JS CLI tests should pass.")@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:23
    runAllTestsConsole()@/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:55
    @/home/nrdufour/tmp/refuge/deps/couch_core/test/couch_dev/test/javascript/cli_runner.js:59
Failed to execute script.
ok
make: **\* [js] Error 1
nrdufour@ubuntu32:~/tmp/refuge/deps/couch_core$

**Comment by nrdufour** [comment]
I ran it a third time and I got this time just the #63 failing ... Not consistent at all!

**Comment by nrdufour** [comment]
OK a last round ... and NO failure!!

The only difference I can see here is perhaps the load on the system that could explain those discrepancies.

**Comment by benoitc** [comment]
I'm thinking those errors are due to timing issues maybe related to _restart. Which is annoying since it means we can't rely really on these tests for continuous integration. Maybe we should take the bull by the horns and rewrite these tests in pure erlang and also remove this _restart function. Thoughts?

**Comment by benoitc** [comment]
is this latest erlang from ubuntu or another one?

**Comment by benoitc** [comment]
I couldn't reproduce on Ubuntu 12.04 i386 beta32 with the official  Debian package of Erlang.

**Comment by nrdufour** [comment]
It was Erlang R14B04 on ubuntu 12.04 beta 32 bit.

Not surprised you can't reproduce.
Let's close this issue.
