### ISSUE TITLE
system databases

### ISSUE THREAD

**Issue by benoitc** [rcouch/couch_core#9]
Hi all, 

I would like to introduce a new kind of databases in the couch core. This database would take care about databases metadata, users, hooks, replications tasks and such. Something similar to postgres system catalogs: 

http://www.postgresql.org/docs/8.2/static/catalogs.html

Such databases would be only accessible by admins and HTTP resources. Normal users won't have direct access to them. Only through the HTTP API.

I'm looking for a way to name them. I don't want to prefix them by "_" to distinct db resources from normal paths.

After discussing on IRC, current choices are available:
1. `rc_*` : rc for rcouch.
2. `sys_`
3.  `rcouch/` : wwith the problem that such path will need to be encoded for admins accessing at api level (not a big problem though)

So far 1 & 3 have my preferences. Having branding ini the name is a better than a generic name like `sys` there. Maybe 3 should be choosed over the 1 because it gives more informations and doesn't pollute other namespaces.

Thoughs? Please +1 your solution or provides an another :)

**Comment by ghost** [comment]
'+ 1' for rc_*

I don't like idea or url encoding the slash or giving anymore meaning to db name

**Comment by nrdufour** [comment]
I like small prefixes so +1 for rc_\* as well.
